### ISSUE TITLE
Unable to install plugin

### ISSUE THREAD

**Issue by lindholm** [ponder-lab/Optimize-Java-8-Streams-Refactoring#194]
I get:
```
Cannot complete the install because one or more required items could not be found.
  Software being installed: Optimize Streams Refactoring 0.13.0.201804272226 (edu.cuny.hunter.optimize.stream.refactoring.feature.group 0.13.0.201804272226)
  Missing requirement: Optimize Streams Refactoring 0.13.0.201804272226 (edu.cuny.hunter.optimize.stream.refactoring.feature.group 0.13.0.201804272226) requires 'edu.cuny.citytech.refactoring.common.core [1.1.0,2.0.0)' but it could not be found
```
Eclipse 4.7.3a

**Comment by khatchad** [comment]
Thanks for the report, @lindholm! I'll look into it. In the meantime, I believe you can [install that dependency manually](https://github.com/ponder-lab/Optimize-Java-8-Streams-Refactoring#dependencies) using the update site https://raw.githubusercontent.com/ponder-lab/Common-Eclipse-Java-Refactoring-Framework/master/edu.cuny.citytech.refactoring.common.updatesite.

**Comment by khatchad** [comment]
Couldn't repro this using the marketplace link. I'll try the update site.

**Comment by khatchad** [comment]
It's also possible that that dependency is lurking somewhere on my local machine and is being matched during the install process.

**Comment by khatchad** [comment]
Found this in the `content.xml` file that is used in the update site:
```
<required namespace='org.eclipse.equinox.p2.iu' name='edu.cuny.citytech.refactoring.common.core' range='[1.1.0,2.0.0)'/>
```

**Comment by khatchad** [comment]
I was able to get a different dependency error using the update site.

**Comment by khatchad** [comment]
Filed https://bugs.eclipse.org/bugs/show_bug.cgi?id=534321.

**Comment by khatchad** [comment]
Hi @lindholm. I included the dependencies inside the feature. It should help with the problem until we get things square with the Eclipse bug above. Please feel free to re-open if you still are experiencing issues. Please install version 0.15.0.
