### ISSUE TITLE
Profile tool for performance

### ISSUE THREAD

**Issue by khatchad** [ponder-lab/Optimize-Java-8-Streams-Refactoring#73]
Why is the tool taking the most time?

**Comment by khatchad** [comment]
@saledouble We are done with this correct?

**Comment by saledouble** [comment]
>We are done with this correct? 
Yes.

**Comment by khatchad** [comment]
Great. Can you please enter your results and mark it as complete?

**Comment by saledouble** [comment]
I've tested 3 projects: `threeten-extra`, `streamql` and `mondas`. Most of time was cost by rule solver.

![image](https://user-images.githubusercontent.com/10117031/44292223-68da7c80-a251-11e8-93ad-2b3233607acb.png)

![image](https://user-images.githubusercontent.com/10117031/44292228-7132b780-a251-11e8-9985-464951479d5c.png)

**Comment by saledouble** [comment]
>Can you please enter your results and mark it as complete?

I've entered the results, but I have no permission to close the issue.

**Comment by saledouble** [comment]
The unit is `milliseconds`.

**Comment by khatchad** [comment]
https://github.com/ponder-lab/Stream-Performance-Refactoring-Paper/commit/d25c5f0b185820d52db2d11a79cf680a1629579b
